# Generated by Django 5.0.7 on 2024-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ManyToManyField(related_name='transactions_in', to='finance_app.category'),
        ),
    ]
