name: Finance Tracker API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.7
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: tracker
          POSTGRES_PASSWORD: Ameer$571
          POSTGRES_DB: finance_tracker
        options: > 
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -U tracker; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up database
      run: |
        export PGPASSWORD=Ameer$571
        psql -h localhost -U tracker -c "CREATE DATABASE finance_tracker;"

    - name: Run tests
      run: |
        python manage.py test