name: Finance Tracker API

on:
    push:
        branches: [ main ]
jobs:
  test:
    services:
      postgres:
        image: postgres:15.7
        env:
          POSTGRES_USER: tracker
          POSTGRES_PASSWORD: Ameer$571
          POSTGRES_DB: finance_tracker
        ports:
          - '5432:5432'

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: finance_tracker.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
